### ISSUE TITLE
Log Entry Create/Edit

### ISSUE THREAD

**Issue by Volskaar** [Norace2002/SWEN-2#16]
Add interface for log entry creation
(maybe popup?)

**Comment by Norace2002** [comment]
- Created CreateTourLog.fxml
- Created EditTourLog.fxml
- Added Popup functionality in RouteWindowController -> 

//////////////////////////////////////////////////////////////////////////////////////////////////////
public void loadCreateTourLogWindow(ActionEvent event) {
        System.out.println("load route Log creation window");

        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/at/fhtw/tourPlanner/createTourLog.fxml"));
            Parent root = loader.load();
            CreateTourLogController controller = loader.getController();

            Stage popupStage = new Stage();
            popupStage.initOwner((Stage)((Node)event.getSource()).getScene().getWindow());
            popupStage.initModality(Modality.WINDOW_MODAL);

            Scene scene = new Scene(root);
            popupStage.setScene(scene);

            controller.setStage(popupStage);

            popupStage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
//////////////////////////////////////////////////////////////////////////////////////////////////////

-

**Comment by Norace2002** [comment]
- extracted input from popup and created Log entry
-  TODO: implement Mediator functionality

**Comment by Norace2002** [comment]
machted log model with db and fixed bugs
