### ISSUE TITLE
log4j logging

### ISSUE THREAD

**Issue by Volskaar** [Norace2002/SWEN-2#27]
add logging functionality with log4j

**Comment by Norace2002** [comment]
- added logger functionality to frontend
- added log4j2 directly to  ressources folder (very important)
- defined logginf level so every level is active
- defined logger in files :
            import org.apache.logging.log4j.LogManager;
            import org.apache.logging.log4j.Logger;

            private static final Logger logger = LogManager.getLogger(LogService.class);

**Comment by Norace2002** [comment]
- added logger functionality to backend where it seemed necessary
