### ISSUE TITLE
Route List

### ISSUE THREAD

**Issue by Volskaar** [Norace2002/SWEN-2#5]
1. Controller goes to ViewModel and demands a list of Labels for Routes
2. ViewModel takes model for RouteEntries
3. ViewModel asks backend for RouteEntries
4. ViewModel builds list of Labels from Entries in DB
5. ViewModel returns list of Lables to Controller
6. Controller displays list of Labels in ScrollPane

info: routename would probably be PK for routeEntries in DB

**Comment by Volskaar** [comment]
Implemented:
- connection of Controllers with Mediator
- ViewModel handles ObservableList with Hashmap

Missing:
- deleting entries
- editing entries
- taking over RouteEntry data into display

**Comment by Norace2002** [comment]
missing elements solved
